<?php if (!$input->isHidden() && $input->hasRowBegin()): ?>
<div class="field is-horizontal<?= $input->getLocale() ? ' row-localized' : '' ?>"<?= $input->getLocale() ? ' data-locale="'.$input->getLocale().'"' : '' ?>>
    <?= $this->fetch(':form/label', ['input' => $input]) ?>
<?php endif ?>
<?= $this->fetch(':form/input', ['input' => $input]) ?>
<?= !$input->isHidden() && $input->hasRowEnd() ? "</div>" : "" ?>